# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

env = HYPRCURSOR_THEME,Bibata-Modern_Classic
envd = HYPRCURSOR_SIZE,18
env = XCURSOR_THEME,Bibata-Modern_Classic
envd = XCURSOR_SIZE,18
env = QT_CURSOR_THEME,Bibata-Modern_Classic
envd = QT_CURSOR_SIZE,18
