# Btop Wallust Theme

# Main background
theme[main_bg]="#080000"

# Main text color
theme[main_fg]="#FFEFA6"

# Title color for boxes
theme[title]="#FFEFA6"

# Highlight color for selected items
theme[hi_fg]="#FF6F1B"

# Background color of selected item
theme[selected_bg]="#AD9C53"

# Text color of selected item
theme[selected_fg]="#F6DF77"

# Color of inactive/disabled text
theme[inactive_fg]="#AD9C53"

# Color of text appearing on top of graphs
theme[graph_text]="#FFEFA6"

# Misc colors for processes, etc.
theme[proc_misc]="#FFD000"

# Cpu box outline color
theme[cpu_box]="#FF6F1B"

# Memory box outline color
theme[mem_box]="#23901C"

# Net box outline color
theme[net_box]="#2465AC"

# Proc box outline color
theme[proc_box]="#87D33C"

# Box divider line and small boxes line color
theme[div_line]="#AD9C53"

# Temperature graph colors
theme[temp_start]="#23901C"
theme[temp_mid]="#2465AC"
theme[temp_end]="#99341F"

# CPU graph colors
theme[cpu_start]="#23901C"
theme[cpu_mid]="#FF6F1B"
theme[cpu_end]="#FFD000"

# Mem/Disk free meter
theme[free_start]="#23901C"
theme[free_mid]="#23901C"
theme[free_end]="#23901C"

# Mem/Disk cached meter
theme[cached_start]="#FF6F1B"
theme[cached_mid]="#FF6F1B"
theme[cached_end]="#FF6F1B"

# Mem/Disk available meter
theme[available_start]="#2465AC"
theme[available_mid]="#2465AC"
theme[available_end]="#2465AC"

# Mem/Disk used meter
theme[used_start]="#99341F"
theme[used_mid]="#99341F"
theme[used_end]="#99341F"

# Download graph colors
theme[download_start]="#FF6F1B"
theme[download_mid]="#FF6F1B"
theme[download_end]="#FFD000"

# Upload graph colors
theme[upload_start]="#FF6F1B"
theme[upload_mid]="#FF6F1B"
theme[upload_end]="#87D33C"
