# Btop Wallust Theme

# Main background
theme[main_bg]="#0E0E10"

# Main text color
theme[main_fg]="#F5FBEC"

# Title color for boxes
theme[title]="#F5FBEC"

# Highlight color for selected items
theme[hi_fg]="#759F08"

# Background color of selected item
theme[selected_bg]="#A2A99A"

# Text color of selected item
theme[selected_fg]="#E8F1DC"

# Color of inactive/disabled text
theme[inactive_fg]="#A2A99A"

# Color of text appearing on top of graphs
theme[graph_text]="#F5FBEC"

# Misc colors for processes, etc.
theme[proc_misc]="#A5F43D"

# Cpu box outline color
theme[cpu_box]="#759F08"

# Memory box outline color
theme[mem_box]="#AA2D20"

# Net box outline color
theme[net_box]="#258873"

# Proc box outline color
theme[proc_box]="#402CF6"

# Box divider line and small boxes line color
theme[div_line]="#A2A99A"

# Temperature graph colors
theme[temp_start]="#AA2D20"
theme[temp_mid]="#258873"
theme[temp_end]="#195EAA"

# CPU graph colors
theme[cpu_start]="#AA2D20"
theme[cpu_mid]="#759F08"
theme[cpu_end]="#A5F43D"

# Mem/Disk free meter
theme[free_start]="#AA2D20"
theme[free_mid]="#AA2D20"
theme[free_end]="#AA2D20"

# Mem/Disk cached meter
theme[cached_start]="#759F08"
theme[cached_mid]="#759F08"
theme[cached_end]="#759F08"

# Mem/Disk available meter
theme[available_start]="#258873"
theme[available_mid]="#258873"
theme[available_end]="#258873"

# Mem/Disk used meter
theme[used_start]="#195EAA"
theme[used_mid]="#195EAA"
theme[used_end]="#195EAA"

# Download graph colors
theme[download_start]="#759F08"
theme[download_mid]="#759F08"
theme[download_end]="#A5F43D"

# Upload graph colors
theme[upload_start]="#759F08"
theme[upload_mid]="#759F08"
theme[upload_end]="#402CF6"
