# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

env = HYPRCURSOR_THEME,ComixCursors-Slim-White
envd = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,ComixCursors-Slim-White
envd = XCURSOR_SIZE,24
env = QT_CURSOR_THEME,ComixCursors-Slim-White
envd = QT_CURSOR_SIZE,24
